{"uuid":"97a983ab-9ac2-48a0-82a6-02e82dd59d64","historyId":"ff1d262532669e3222fbec71c22c544","fullName":"TestClass.NewLrLoginpage.VerifyLoginPageOFLR","labels":[{"name":"package","value":"TestClass.NewLrLoginpage"},{"name":"testClass","value":"TestClass.NewLrLoginpage"},{"name":"testMethod","value":"VerifyLoginPageOFLR"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"TestClass.NewLrLoginpage"},{"name":"host","value":"LAPTOP-O6ECEAOP"},{"name":"thread","value":"25832@LAPTOP-O6ECEAOP.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"VerifyLoginPageOFLR","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Login failed due to unexpected error.","trace":"java.lang.AssertionError: Login failed due to unexpected error.\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat PomClass.LRLOGIN.login(LRLOGIN.java:142)\r\n\tat TestClass.NewLrLoginpage.VerifyLoginPageOFLR(NewLrLoginpage.java:22)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n\tat org.testng.TestRunner.run(TestRunner.java:621)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\n"},"stage":"finished","steps":[],"attachments":[{"name":"LR_LOGIN_FAILURE","source":"e2c390da-0bb6-4730-8e04-1aa84af96b2a-attachment"}],"parameters":[],"start":1748841207003,"stop":1748841242739}